version: 2.1
orbs:
  node: circleci/node@5.0.2

executors:
  my-node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build_and_test:
    executor: my-node-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
      - run:
          command: npm run cypress:runner
      - persist_to_workspace:
          root: ~/project
          paths: .

workflows:
  test_my_app:
    jobs:
      - build_and_test
