version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor:
      name: my-node-executor
      docker:
        - image: circleci/node:14

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
      - run:
          command: npm run cypress:runner
      - persist_to_workspace:
          root: ~/project
          paths: .

workflows:
  test_my_app:
    jobs:
      - build_and_test
